[package]
name = "github_issue_roulette"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
rand = "0.9.1"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
